---
engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  # sasslint:
  #   enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.scss"
exclude_paths:
- config/**/*
- db/**/*
- script/**/*
- spec/**/*
- test/**/*
- vendor/**/*
