<%
# Copied from Heroku database.yml.
# Populates from DATABASE_URL or database_url in settings.local.yml.

require 'cgi'
require 'uri'

begin
  uri = URI.parse(Rails.configuration.database_url)
rescue URI::InvalidURIError
  raise "Invalid Rails.configuration.database_url: #{Rails.configuration.database_url}"
end

def attribute(name, value, force_string = false)
  if value
    value_string =
      if force_string
        '"' + value + '"'
      else
        value
      end
    "#{name}: #{value_string}"
  else
    ""
  end
end

adapter = uri.scheme
adapter = "postgresql" if adapter == "postgres"
adapter = "mysql2" if adapter == "mysql"

database = (uri.path || "").split("/")[1]

username = uri.user
password = uri.password

host = uri.host
port = uri.port

params = CGI.parse(uri.query || "")

params['reaping_frequency'] ||= [Rails.configuration.db.reaping_frequency]
params['pool'] ||= [Rails.configuration.db.pool_size]

%>

<%= ENV["RAILS_ENV"] || ENV["RACK_ENV"] || 'development' %>:
  <%= attribute "adapter",  adapter %>
  <%= attribute "database", database %>
  <%= attribute "username", username %>
  <%= attribute "password", password, true %>
  <%= attribute "host",     host %>
  <%= attribute "port",     port %>

<% params.each do |key, value| %>
  <%= key %>: <%= value.first %>
<% end %>
