# Use settings.local.yml to store settings for your development environment.
# This is an alternative to setting these in environment variables that are loaded by settings.yml

# If there's a section whose items you're not going to populate, such as sentry.dsn, you must remove the
# entire section, so all of sentry in this example.

development: &development
  app:
    assets:
      serve_static_files: true
    consider_requests_local: true
    fqdn: rails-5-example.dev
    force_ssl: false
  better_errors:
    editor: sublime
    trusted_ip: 192.168.0.0/16 127.0.0.0/8
  #leave cookie domain blank when we might be accessing the same config via different domains (rails-5-example.dev and rails-5-example.local)
  cookie_domain: rails-5-example.dev
  database_url: postgresql://rails5example_dev:rails5example_dev@localhost:5432/rails5example_dev?timeout=5000
  db:
    pool_size: 50
  email: &development_email_defaults
    delivery_method: letter_opener
    sender_address: app@example.com
    sender_name: 'ExampleApp'
    recipients:
      support: app-support@example.com
  secret_token: asdf1234
  slim_templating:
    pretty_html_formatting: true

test:
  database_url: postgresql://rails5example_test:rails5example_test@localhost:5432/rails5example_test?timeout=5000
  email:
    <<: *development_email_defaults
    delivery_method: test
  secret_token: asdf1234


# The following sections are here for when you must run in production or staging mode in order to reproduce a problem
# that is not reproducible in development.

# production:
#   <<: *development

# staging:
#   <<: *development
