defaults: &defaults
  app:
    fqdn: <%= ENV['RAILS_APP_FQDN'] || 'app.example.com' %>
    force_ssl: <%= ENV['RAILS_APP_FORCE_SSL'] %>
    name: <%= ENV['RAILS_APP_NAME'] || 'ExampleApp' %>
    log_to_stdout: <%= ENV['LOG_TO_STDOUT'] %>
  assets:
    serve_static_files: <%= ENV['SERVE_STATIC_FILES'] %>
    version: <%= ENV['ASSETS_VERSION'] || '0.0.1' %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>

development:
  <<: *defaults

test:
  <<: *defaults
  assets:
    serve_static_files: true

staging:
  <<: *defaults

production:
  <<: *defaults
