defaults: &defaults
  app:
    assets:
      serve_static_files: <%= ENV['SERVE_STATIC_FILES'] %>
      version: <%= ENV['ASSETS_VERSION'] || '0.0.1' %>
    consider_requests_local: <%= ENV['CONSIDER_REQUESTS_LOCAL'] %>
    force_ssl: <%= ENV['RAILS_APP_FORCE_SSL'] %>
    fqdn: <%= ENV['RAILS_APP_FQDN'] || 'app.example.com' %>
    log_level: <%= ENV['LOG_LEVEL'] || 'info' %>
    log_to_stdout: <%= ENV['LOG_TO_STDOUT'] %>
    name: <%= ENV['RAILS_APP_NAME'] || 'ExampleApp' %>
  better_errors:
    editor: sublime
    trusted_ip: <%= ENV['TRUSTED_IP'] %>
  cookie_domain: <%= ENV['COOKIE_DOMAIN'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  db:
    reaping_frequency: <%= (ENV['DB_REAPING_FREQUENCY_SECONDS'] || 60).to_i %>
    pool_size: <%= (ENV['DB_POOL_SIZE'] || 25).to_i %>
    timeout: <%= (ENV['DB_TIMEOUT_SECONDS'] || 5).to_i %>
    encoding: <%= (ENV['DB_ENCODING'] || 'utf8') %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  slim_templating:
    pretty_html_formatting: <%= ENV['SLIM_PRETTY_HTML'] %>

development:
  <<: *defaults

test:
  <<: *defaults
  assets:
    serve_static_files: true

staging:
  <<: *defaults

production:
  <<: *defaults
