defaults: &defaults
  app: &app_defaults
    assets: &app_asset_defaults
      compile: <%= ENV['COMPILE_MISSING_ASSETS_ON_REQUEST'] %>
      serve_static_files: <%= ENV['SERVE_STATIC_FILES'] %>
      version: <%= ENV['ASSETS_VERSION'] || '0.0.1' %>
    consider_requests_local: <%= ENV['CONSIDER_REQUESTS_LOCAL'] %>
    copyright_author: <%= ENV['COPYRIGHT_AUTHOR'] || 'K&R Software, LLC'%>
    force_ssl: <%= ENV['RAILS_APP_FORCE_SSL'] %>
    fqdn: <%= ENV['RAILS_APP_FQDN'] || 'app.example.com' %>
    log_level: <%= ENV['LOG_LEVEL'] || 'info' %>
    log_to_stdout: <%= ENV['LOG_TO_STDOUT'] %>
    name: <%= ENV['RAILS_APP_NAME'] || 'ExampleApp' %>
  better_errors:
    editor: sublime
    trusted_ip: <%= ENV['TRUSTED_IP'] %>
  cookie_domain: <%= ENV['COOKIE_DOMAIN'] %>
  database_url: <%= ENV['DATABASE_URL'] %>
  db:
    reaping_frequency: <%= (ENV['DB_REAPING_FREQUENCY_SECONDS'] || 60).to_i %>
    pool_size: <%= (ENV['DB_POOL_SIZE'] || 25).to_i %>
    timeout: <%= (ENV['DB_TIMEOUT_SECONDS'] || 5).to_i %>
    encoding: <%= (ENV['DB_ENCODING'] || 'utf8') %>
  default_timezone: <%= ENV['DEFAULT_TIMEZONE'] || 'UTC' %>
  email: &email_defaults
    delivery_method: <%= ENV['EMAIL_DELIVERY_METHOD'] %>
    sender_address: <%= ENV['EMAIL_DEFAULT_FROM'] || ENV['EMAIL_FROM_ADDRESS'] || ENV['EMAIL_DEFAULT_SENDER_ADDRESS'] %>
    sender_name: <%= ENV['EMAIL_DEFAULT_FROM'] || ENV['EMAIL_FROM_NAME'] || ENV['EMAIL_DEFAULT_SENDER_NAME'] %>
    recipients:
      support: <%= ENV['EMAIL_RECIPIENTS_SUPPORT'] %>
  postmark:
    api_key: <%= ENV['POSTMARK_API_KEY'] %>
  redis:
    url: <%= ENV['REDIS_URL'] || 'redis://127.0.0.1:6379/0' %>
  redis_browser:
    web:
      mount_point: <%= ENV['REDIS_BROWSER_WEB_MOUNT_POINT'] || "/redis-browser" %>
      username: <%= ENV['REDIS_BROWSER_WEB_USERNAME'] || 'admin'  %>
      password: <%= ENV['REDIS_BROWSER_WEB_PASSWORD'] || 'password'  %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  sentry:
    dsn: <%= ENV['SENTRY_DSN'] %>
    javascript_enabled: <%= ENV['SENTRY_JAVASCRIPT_ENABLED'] %>
  sidekiq:
    web:
      mount_point: <%= ENV['SIDEKIQ_WEB_MOUNT_POINT'] || "/sidekiq" %>
      username: <%= ENV['SIDEKIQ_WEB_USERNAME'] || 'admin'  %>
      password: <%= ENV['SIDEKIQ_WEB_PASSWORD'] || 'password'  %>
    redis:
      url: <%= ENV['SIDEKIQ_REDIS_URL'] %>
  slim_templating:
    pretty_html_formatting: <%= ENV['SLIM_PRETTY_HTML'] %>

development:
  <<: *defaults

test:
  <<: *defaults
  app:
    <<: *app_defaults
    assets:
      <<: *app_asset_defaults
      serve_static_files: true
  email:
    <<: *email_defaults
    delivery_method: test

staging:
  <<: *defaults

production:
  <<: *defaults
